### ISSUE TITLE
Migrate aws-sdk-go v1 to v2

### ISSUE THREAD

**Issue by JoseAngel1196** [godaddy/asherah#1031]
**Is your feature request related to a problem? Please describe.**

Are there any plans for when you are planning to migrate from aws-sdk-go v1 to v2? The AWS team has already set a deadline ([reference](https://github.com/aws/aws-sdk-go#:~:text=We%20announced%20the%20upcoming%20end%2Dof%2Dsupport%20for%20AWS%20SDK%20for%20Go%20(v1).%20We%20recommend%20that%20you%20migrate%20to%20AWS%20SDK%20for%20Go%20v2.%20For%20dates%2C%20additional%20details%2C%20and%20information%20on%20how%20to%20migrate%2C%20please%20refer%20to%20the%20linked%20announcement.)) for when they plan to stop supporting the v1 AWS SDK for Go. They're encouraging everyone to migrate to v2.

**Comment by JoseAngel1196** [comment]
Happy to work on this task, just want to know if this is being tracked somewhere by the team.

**Comment by sushantmimani** [comment]
> Happy to work on this task, just want to know if this is being tracked somewhere by the team.

Hi @JoseAngel1196! While we're aware of this, no development has started yet. Please feel free to submit a PR for this. We'd love the contribution! 😄

**Comment by JoseAngel1196** [comment]
> > Happy to work on this task, just want to know if this is being tracked somewhere by the team.
> 
> Hi @JoseAngel1196! While we're aware of this, no development has started yet. Please feel free to submit a PR for this. We'd love the contribution! 😄

oh nice -- yes I can take this. Will work on this!

**Comment by JoseAngel1196** [comment]
> > Happy to work on this task, just want to know if this is being tracked somewhere by the team.
> 
> Hi @JoseAngel1196! While we're aware of this, no development has started yet. Please feel free to submit a PR for this. We'd love the contribution! 😄

can you please assign the issue to me?

**Comment by JoseAngel1196** [comment]
Hey @sushantmimani @aka-bo I want to know what y'all think about this:

should I consider creating a BREAKING CHANGE for this change? that means moving DynamoDB v1 client to v2?

OR

should i create a separate module for the v2 next to the v1? we might be able to reuse some of the code already in https://github.com/godaddy/asherah/blob/main/go/appencryption/pkg/persistence/dynamodb.go

**Comment by sushantmimani** [comment]
> Hey @sushantmimani @aka-bo I want to know what y'all think about this:
> 
> should we consider creating a BREAKING CHANGE for this change? that means moving DynamoDB v1 client to v2
> 
> OR
> 
> should i create a separate module for the v2 next to the v1? we might be able to reuse some of the code already in https://github.com/godaddy/asherah/blob/main/go/appencryption/pkg/persistence/dynamodb.go

Hi @JoseAngel1196 , we're discussing this internally and will let you know soon.

**Comment by sushantmimani** [comment]
Hi @JoseAngel1196! We **do not** want to make this a breaking change. A separate package for v2 would be great. We were thinking of something along the lines of:
```bash
.
├── cmd
│   └── example
├── integrationtest
│   ├── persistence
│   │   ├── persistencetest
│   └── traces
├── internal
├── pkg
│   ├── crypto
│   │   └── aead
│   ├── kms
│   ├── log
│   └── persistence
├── plugins
│   └── aws-v1
│   │   ├── kms
│   │   └── persistence
│   └── aws-v2
│       ├── kms
│       └── persistence
├── scripts
```
We're currently working on the `aws_v1` changes and you're welcome to start on the aws_v2 changes.

**Comment by JoseAngel1196** [comment]
> Hi @JoseAngel1196! We **do not** want to make this a breaking change. A separate package for v2 would be great. We were thinking of something along the lines of:
> 
> ```shell
> .
> ├── cmd
> │   └── example
> ├── integrationtest
> │   ├── persistence
> │   │   ├── persistencetest
> │   └── traces
> ├── internal
> ├── pkg
> │   ├── crypto
> │   │   └── aead
> │   ├── kms
> │   ├── log
> │   └── persistence
> ├── plugins
> │   └── aws-v1
> │   │   ├── kms
> │   │   └── persistence
> │   └── aws-v2
> │       ├── kms
> │       └── persistence
> ├── scripts
> ```
> 
> We're currently working on the `aws-v1` changes and you're welcome to start on the `aws-v2` changes.

Amazing, I'll start working on this ASAP!

**Comment by aka-bo** [comment]
See #1041 for the current state of the `aws-v1` work
