### ISSUE TITLE
ALL: Make metastore table name configurable

### ISSUE THREAD

**Issue by rohitjha** [godaddy/asherah#195]
When working with different systems/projects in one AWS account, since DynamoDB global table names have to be unique at the account level, having a single metastore table named `EncryptionKey` can be problematic because:

- we would have to adjust the table's read-write capacities when changing the number of systems/projects in that account
- cleaning up data and keys isn't as simple as deleting a table, and can potentially cause a loss of data when not done perfectly

It'll be great if the metastore table name is configurable with the name defaulting to the current values of `EncryptionKey` (DynamoDB implementation) and `encryption_key` (RDBMS implementation) for all languages.

**Comment by nikoo28** [comment]
Go-server changes completed via https://github.com/godaddy/asherah/pull/225
