### ISSUE TITLE
Server: take a dynamodb endpoint url as a config parameter

### ISSUE THREAD

**Issue by cfogg** [godaddy/asherah#196]
When developing locally, it is helpful to have the option of running a local DynamoDB instance. It would be great to be able to use this with the Go or Java Asherah server.

I think we'd want an env variable to set the URL, then in `server.go`, pass that value in the AWS Config object to set the endpoint.

Another option for developing locally is to use the in-memory metastore, but that has the limitation that intermediate keys are not persisted between sessions. I had wondered if maybe swapping in a sqlite mode to replace in-memory would be a quick win; I think you'd get to re-use all the rdbms code you have, but you'd be able to persist the metastore to file, and re-use that across invocations of the containers, as well as just across sessions. It's possible this a different feature request, but it would also be a good option for developing locally.

**Comment by nikoo28** [comment]
Changes in `go` server have been completed. Details available at https://github.com/godaddy/asherah/tree/master/server/go

**Comment by sushantmimani** [comment]
Feature added by #217
