### ISSUE TITLE
[C#] Improve methodology for skipping tests

### ISSUE THREAD

**Issue by aka-bo** [godaddy/asherah#204]
Ideally skipped tests should be reported in some way. Any thoughts on replacing these `if\return` blocks with something like [xunit.skippablefact](https://github.com/AArnott/Xunit.SkippableFact)?

_Originally posted by @aka-bo in https://github.com/godaddy/asherah/pull/198_

**Comment by jgowdy** [comment]
I've actually made this change in https://github.com/godaddy/asherah/pull/309

The relevant tests are using SkippableFact

**Comment by aka-bo** [comment]
That you did. Thanks!
