### ISSUE TITLE
Dependency on StyleCop creates masses of build warnings

### ISSUE THREAD

**Issue by lyricnz** [godaddy/asherah#259]
When adding Asherah AppEncryption to our project via NuGet, it drags in Asherah.Crypto which in turn has a dependency on StyleCop.Analyzers.  This creates hundreds of warnings in our project builds, clogging logs and making the IDE very messy / hard-to-ues.

Is there some way in which we can disable StyleCop completely?  We don't it running on our projects.

I tried to find ways to turn this off myself, but was unsuccessful.

**Comment by nikoo28** [comment]
looks like there is a way to have some libraries for development use only. this is being worked upon.

**Comment by lyricnz** [comment]
Version 0.1.5 appears to resolve this. Thanks!
