### ISSUE TITLE
Allow for pluggable SecureMemory implementation

### ISSUE THREAD

**Issue by lyricnz** [godaddy/asherah#290]
**Is your feature request related to a problem? Please describe.**
The default implementation of SecureMemory uses mlock which is not available/usable on all platforms. In particular, on AWS Lambda, it is only 64KB - which precludes use of any caching, and may make the library unreliable due to unpredictable and opaque usage of mlock. See https://github.com/godaddy/asherah/issues/260

**Describe the solution you'd like**
Allow users of the library to provide their own implementation of an interface for SecureMemory.

**Describe alternatives you've considered**
I know that having secure memory allocators is a fundamental part of your design goals, but the current implementation is not usable in some circumstances, and this is not solvable without completely forking the library and hacking the SecureMemory implementation. 
Also, there is no metric/audit available to tell what is allocating securememory, when and how much, and when it's freed.

**Additional context**
Even if all caching is disabled, concurrency within the same runtime could mean that more securememory is used than expected, resulting in a crash.

**Comment by sushantmimani** [comment]
@lyricnz The team is currently working on https://github.com/godaddy/asherah/pull/286 which should be helpful while running Asherah on AWS Lambda

**Comment by jgowdy** [comment]
Yes, we are shifting the strategy for the allocators to move away from using page protections with full 4KB mmap sized pages, and instead use encryption with page protection on the key page.  We'll need to port the work from #286 to Java if that's what you're using as described in #260.  This drops the mlocked page requirement to only a single digit number of pages (1 key page plus N concurrent decryption pages).

**Comment by lyricnz** [comment]
Excellent!

**Comment by jgowdy** [comment]
Oh, if you're on C#, I literally have this work in progress here:

Phase 1: https://github.com/godaddy/asherah/pull/286
Phase 2: https://github.com/godaddy/asherah/pull/300

**Comment by lyricnz** [comment]
I've sent details about that to the developers that were using it, but they haven't had time to investigate it yet.
