### ISSUE TITLE
[Go] Golang: Degraded, unrecoverable performance of DRR decrypt times after RevokeCheckInterval expires.

### ISSUE THREAD

**Issue by keperry** [godaddy/asherah#385]
**Describe the bug**
Golang: Degraded, unrecoverable performance of DRR decrypt times after RevokeCheckInterval expires.

We noticed some large increases in DRR decrypt times - 99 percentile of `ael.drr.decrypt` (we were using the metrics from the library w/prometheus and grafana).  It appeared that the app would never recover.  We were trying to upgrade from an older version (not in this repo) to the latest version v0.2.1
See screenshot below:
![DataFabric_-_Encryption_Database_Metrics_-_Grafana_and_mgntapi_–_encryption_go](https://user-images.githubusercontent.com/1618767/126328322-5b59a204-3979-41a7-848e-81fed03f3902.png)

**To Reproduce**
1.  Use default crypto policy (RevokeCheckInterval at 60m).  You can reduce this to reduce test timing.  
2. Startup app using this that uses decrypt
3.  At the RefreshCheckInterval, you will see DRR times skyrocket (10x?).  They seem to keep climbing until the app is unusable.

Note:  In PR, I will have a test and benchmark test to reproduce.

**Expected behavior**
We expect that after the RevokeCheckInterval expires that there is a slight hit in performance when the new system/intermediate keys are loaded, but the app should be usable after this point.

**Screenshots**
See above.

PR coming soon.

**Comment by tarkatronic** [comment]
Fixed in #386
