### ISSUE TITLE
[Go] Intermittent encryption errors

### ISSUE THREAD

**Issue by aka-bo** [godaddy/asherah#401]
Reported by @bdittmer-godaddy via PR #400

**Describe the bug**
We have seen intermittent errors encrypting a payload. The error message is:
error decrypting data: cipher: message authentication failed

In this case, it appears that an IK rotates and uses an SK that is about to expire. Next request, the SK expires so it creates a new one but cannot create a new IK for an interval up to the CreateDatePrecision in the specified policy as that would create a duplicate.

**Comment by JoseAngel1196** [comment]
not sure why but I still get this error message from time to time

**Comment by aka-bo** [comment]
Hi @JoseAngel1196, are you working with a DynamoDB Global Table or any other multi-region datastore in a hot/hot configuration?

If so, this error can be avoided by supplying the `WithDynamoDBRegionSuffix` option when [constructing your metastore](https://github.com/godaddy/asherah/tree/main/go/appencryption#dynamodb-metastore).

> WithDynamoDBRegionSuffix configures the DynamoDBMetastore to use a regional suffix for all writes. This feature should be enabled when using DynamoDB global tables to avoid write conflicts arising from the "last writer wins" method of conflict resolution.
