### ISSUE TITLE
Support for Apple Silicon (ARM64)

### ISSUE THREAD

**Issue by lramsudh-godaddy** [godaddy/asherah#404]
**Is your feature request related to a problem? Please describe.**
Your system requirements currently do not support Apple Silicon.

**Describe the solution you'd like**
Can you please allow for Apple Silicon ARM64 support

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by lramsudh-godaddy** [comment]
Hi. Is there a way I can get a java release that includes this change? https://github.com/godaddy/asherah/releases?q=java%2Fappencryption&expanded=true

**Comment by aka-bo** [comment]
This change was included in [Java SecureMemory v0.1.4](https://github.com/godaddy/asherah/releases/tag/java%2Fsecurememory%2Fv0.1.4) and the subsequent [Java AppEncryption v0.3.1](https://github.com/godaddy/asherah/releases/tag/java%2Fappencryption%2Fv0.3.1) release.
