### ISSUE TITLE
[Golang] Refactor Go SecureMemory into separate repo

### ISSUE THREAD

**Issue by zeroaltitude** [godaddy/asherah#47]
AEL-696

- [x] Create separate go-securememory repo in appservices AEL-766
- [x] Make Secret abstract/interface so it's not coupled to memguard AEL-767
- [x] Move any other memguard functionality we're using for SM aspects into new repo AEL-768

AC:

* Separate AE and SM repos exist in app services (DomainBackend can fork, etc as needed)
* Specifically, following changes should be isolated in SM repo:
  * SM abstraction of memguard usage.
    * Secret should be interface, of which memguard is one implementation of. Later OpenSSL may be a replacement one
    * Ideally abstracted by factory pattern (if possible in golang)
  * Should contain other memguard related setup, e.g. core dumps, destroy all keys cleanup

**Comment by jpaskhay** [comment]
This will be handled internally and included in the move of the Go implementation into this repo.
