### ISSUE TITLE
Create separate go-securememory repo in appservices

### ISSUE THREAD

**Issue by zeroaltitude** [godaddy/asherah#48]
Parent: [[Golang] Refactor Go SecureMemory into separate repo](https://github.com/godaddy/asherah/projects/1#card-24181704)

AEL-766

Include any dependency management in go-appencryption needed (if too much, then we can circle back in CI/CD work)

**Comment by jpaskhay** [comment]
This will be handled internally and included in the move of the Go implementation into this repo.
