### ISSUE TITLE
Make Secret abstract/interface so it's not coupled to memguard

### ISSUE THREAD

**Issue by zeroaltitude** [godaddy/asherah#49]
Parent: [[Golang] Refactor Go SecureMemory into separate repo](https://github.com/godaddy/asherah/projects/1#card-24181704)

AEL-767

Refer to notes in story. Ideally we can use factory pattern or whatever equivalent there is in golang to provide this.

We should end up with a Secret, MemguardSecret, and some sort of creational pattern in place such that we can later potentially drop in an OpenSslSecret and the switch is abstracted away from AE library.

**Comment by jpaskhay** [comment]
This will be handled internally and included in the move of the Go implementation into this repo.
