### ISSUE TITLE
Move any other memguard functionality we're using for SM aspects into new repo

### ISSUE THREAD

**Issue by zeroaltitude** [godaddy/asherah#50]
Parent: [[Golang] Refactor Go SecureMemory into separate repo](https://github.com/godaddy/asherah/projects/1#card-24181704)

AEL-768

There are some SM related things (disabling core dumps, destroy all keys hooks?) being done in the encryption.go file. These should be handled and abstracted away in the SM repo instead.

**Comment by jpaskhay** [comment]
This will be handled internally and included in the move of the Go implementation into this repo.
