### ISSUE TITLE
Examine addition of external resources in regression test and create stories for the same

### ISSUE THREAD

**Issue by sushantmimani** [godaddy/asherah#57]
Parent: [Validate that the C# regression test suite is complete and in conformance](https://github.com/godaddy/asherah/projects/1#card-24184752)

AEL-791

Timebox some research on how we’d be able to add support for the following (code changes, how to orchestrate/invoke, etc.):

AWS KMS
DynamoDB
ADO

**Comment by nikoo28** [comment]
Decided on the approach
- Use yaml files for configuration management
- Invoke using `dotnet test` and Read environment variables from command line
- Code changes would include setup of metastore mock to delegate calls to actual metastore objects. Same with kmsMocks.
