### ISSUE TITLE
Use external CICD to build and deploy distributables

### ISSUE THREAD

**Issue by sushantmimani** [godaddy/asherah#63]
AEL-787

AC:
From the Asherah repo, build and deploy using the chosen external CICD service

- [x] Spike on CircleCI Monorepo (multi language, images)
- [x] Spike research on other public CICD alternatives
- [x] Spike research on artifact deployment
- [x] Evaluate existing helper scripts wrt external cicd
- [x] Implement Java Secure Memory CI
- [x] Implement Java App Encryption CI
- [x] Implement Java Reference App CI
- [x] Implement Java Test App CI
- [x] Implement C# Logging CI
- [x] Implement C# Secure Memory CI
- [x] Implement C# App Encryption CI
- [x] Implement C# Reference App CI

**Comment by jpaskhay** [comment]
We ended up settling on CircleCI. If we end up needing to change our solution for whatever reason, we can port as needed.
