### ISSUE TITLE
Spike research on other public CICD alternatives

### ISSUE THREAD

**Issue by sushantmimani** [godaddy/asherah#64]
Parent: [Use external CICD to build and deploy distributables](https://github.com/godaddy/asherah/projects/1#card-24189513)

AEL-860

Suggested others to investigate/compare:

- Circle CI (current choice)
- Cirrus CI
- AppVeyor
- Travis CI

**Comment by fkorotkov** [comment]
Since you have a monorepo with different languages that seems to be independent. You might like [`changesInclude` functionality of Cirrus CI](https://cirrus-ci.org/guide/writing-tasks/#supported-functions) in order to skip builds on per-language basis.

**Comment by jpaskhay** [comment]
Thanks, @fkorotkov. We had already started down the path of CircleCI and will be sticking with that for now. If we do end up needing to swap that out (or appending to it), Cirrus CI would definitely be one of the tools we'd consider. Thanks for pointing out that feature!

PS Some of these issues being created are us experimenting with transferring tasks from our internal backlog.

**Comment by jpaskhay** [comment]
We ended up settling on CircleCI. If we end up needing to change our solution for whatever reason, we can port as needed.

From our brief investigation of other solutions, it appears the most popular ones all had tradeoffs from what they handled nicely vs others. Our "unit" tests that run against Docker containers were probably the most problematic to deal with.
