### ISSUE TITLE
[Golang] Memguard research

### ISSUE THREAD

**Issue by nikoo28** [godaddy/asherah#66]
AEL-749

- Upcoming giant PR (https://github.com/awnumar/memguard/pull/81) and its potential impact
  - not using development branch. reassess when they merge it
- Investigate how memguard is being used (looks like for crypto too?)
  - claims not being used for crypto but i see it being used for the random key generation. should verify whether this is needed – come back to this
- Looks like they have encryption in memory as well?
  - that is in development branch 
  - if so, evaluate when merged and how it compares vs openssl
- Appears to also have guard pages adjacent to mlock/mprotect page that contains the secret. need to know impact
  - looks like will cause memory scans to crash the process when those are scanned. will want to call out in documentation for users IMO
- Verify SM aspects
  - how it compares to our implementation from functional and security aspect (i.e. memguard and features we're using)

AC:

    

- Any further research/verification of above notes are handled
- Any changes needed as a result of above are implemented
- Any documentation needed is in place (even MVP/minimal)

**Comment by jpaskhay** [comment]
This will be handled internally and included in the move of the Go implementation into this repo.
