### ISSUE TITLE
Spike research on artifact deployment

### ISSUE THREAD

**Issue by sushantmimani** [godaddy/asherah#71]
Parent: [Use external CICD to build and deploy distributables](https://github.com/godaddy/asherah/projects/1#card-24189513)

AEL-843

Need to know process for uploading to:

- Maven repo
- Nuget repo
- Use other similar projects for reference on what they use for repos
- Upcoming repos (e.g. golang, etc.)
- How are credentials handled for this 
- Finalize a  cross language versioning scheme 
- Will C# approach need to be changed (currently forcing "x.y.a-alpha" to be replaced, similar to java style snapshot)
- Once complete, create additional issues for CD specific work.

**Comment by jpaskhay** [comment]
most of this is now in place via https://github.com/godaddy/asherah/blob/master/.circleci/config.yml

remaining release work will be handled after the Go port is moved into this repo
