### ISSUE TITLE
Implement C# Reference App CI

### ISSUE THREAD

**Issue by sushantmimani** [godaddy/asherah#78]
Parent: [Use external CICD to build and deploy distributables](https://github.com/godaddy/asherah/projects/1#card-24189513)

AEL-855

Using research findings, implement CI part (i.e. don't deploy artifacts yet) for C# Reference App.

Before running builds against external cicd, need to do another prune to verify we don't leak sensitive info into possible build output/logs.

**Comment by jpaskhay** [comment]
this is now in place via https://github.com/godaddy/asherah/blob/master/.circleci/config.yml
