### ISSUE TITLE
Evaluate existing helper scripts wrt external cicd

### ISSUE THREAD

**Issue by sushantmimani** [godaddy/asherah#80]
Parent: [Use external CICD to build and deploy distributables](https://github.com/godaddy/asherah/projects/1#card-24189513)

AEL-844

Currently repos have scripts to do common tasks. Will this cause issues with external cicd? Create stories as needed if we need to overhaul.

**Comment by jpaskhay** [comment]
No, seems pretty common to go this route. Some projects even have their entire build process in shell scripts that get invoked by external cicd.

No issues observed to this point. We can update scripts as needed when we run into issues as they come up.

**Comment by nikoo28** [comment]
Discussed this over a call. It would be a good idea to have scripts for building and testing.

This would help to maintain consistency over projects and the transition (if needed) to different cicd services also becomes easier.
