### ISSUE TITLE
[GoLang] AE: Package Layout and Initial Refactor (first pass)

### ISSUE THREAD

**Issue by sushantmimani** [godaddy/asherah#82]
AEL-771

Initial sweep/pass of SDK package layout to more closely match other languages' functional layout, as well as ensuring core interfaces are in place and names are normalized/consistent.

AC:

- Core package layout is aligned closely with functional layout in other languages as defined in subtasks
- Core interfaces are in place for proper point of abstraction, where appropriate
- Core interfaces and implementing type names are aligned with other languages as much as possible (method/function level likely out of scope and handled later)
- Unit tests updated/relocated accordingly

- [ ] Package: top/root
- [ ] Package: envelope
- [ ] Package: keymanagement
- [ ] Package: persistence
- [ ] Package: crypto
- [ ] Package: keys
- [ ] Package: util

**Comment by cstockton** [comment]
When you complete the first pass mind tagging me for a quick review? Seeing an initial reference implementation will let me gather the projects goals, but feel free to contact me anytime before as well.

Couple points of consideration:
 - naming a package crypto conflicts with std lib, where many core interfaces are defined
 - naming a package "util" is usually frowned upon, stdlib you will see `httputil` `ioutil` instead, for example.
 - top/root should give some indication of purpose, can we do better here?
 - keymanagement is a mouthful, in Go identifiers are fully qualified, so `keymanagement.TheType` could become a bit unsightly. Seeing the types of values it holds may help.
 - finally, less is much better generally speaking in the crypto world if ergonomics and safety are a priority, maybe some of these can begin in `internal/` initially?

**Comment by jpaskhay** [comment]
This was an experiment of trying to consolidate our internal tickets into this public repo. Closing this out as it's been handled internally, and the resulting work will be in our move of the Go codebase here.
