### ISSUE TITLE
Package: top/root

### ISSUE THREAD

**Issue by sushantmimani** [godaddy/asherah#83]
Parent: [[GoLang] AE: Package Layout and Initial Refactor (first pass)](https://github.com/godaddy/asherah/projects/1#card-24232177)

AEL-772

Core interfaces/types:

- AppEncryption (interface)
- Likely assuming interface only parts, i.e. not dealing with load/store at this point?
- AppEncryptionBytesImpl and AppEncryptionJsonImpl (not sure if Impl suffix is convention also used in go)
- AppEncryptionPartition
- AppEncryptionSessionFactory (skip builder / creational pattern aspects for now)

**Comment by jpaskhay** [comment]
This was an experiment of trying to consolidate our internal tickets into this public repo. Closing this out as it's been handled internally, and the resulting work will be in our move of the Go codebase here.
