### ISSUE TITLE
Package: KeyManagement

### ISSUE THREAD

**Issue by sushantmimani** [godaddy/asherah#85]
Parent: [[GoLang] AE: Package Layout and Initial Refactor (first pass)](https://github.com/godaddy/asherah/projects/1#card-24232177)

AEL-774

Core interfaces/types:
- KeyManagementService (interface)
- AwsKeyManagementServiceImpl (not sure if Impl suffix is convention also used in go)
- StaticKeyManagementServiceImpl (not sure if Impl suffix is convention also used in go)

**Comment by cstockton** [comment]
Hello, I suggest taking a look at the Go https://golang.org/doc/effective_go.html documentation, specifically the names section. As proposed you would be imposing this onto users:

```Go
km := keymanagement.NewAwsKeyManagementServiceImpl(...)
```

:scream: 

I think what we want is something like:
```Go
km := awskey.New(awskey.Config{...}) // returns concrete type *awskey.Manager
km := statickey.New(statickey.Config{...}) // returns concrete type *statickey.Manager
  or km := statickey.New(param1, param2, ifConfigStructIsOverkill)
```

You may define an interface satisfied by the `*T` returned by both `awskey` and `statickey` New functions, but at that point you don't need a dedicated package to define `keymanagement.KeyManagementService` - instead the Go interface should define the collective behavior we call key management. Meaning an interface such as:

```Go
package asherah

type KeyManager interface {
    MinimalThings()
    KeyManagersDo()
}
```

Just some initial food for thought here.

**Comment by jpaskhay** [comment]
This was an experiment of trying to consolidate our internal tickets into this public repo. Closing this out as it's been handled internally, and the resulting work will be in our move of the Go codebase here.
