### ISSUE TITLE
Package: Persistence

### ISSUE THREAD

**Issue by sushantmimani** [godaddy/asherah#86]
Parent: [[GoLang] AE: Package Layout and Initial Refactor (first pass)](https://github.com/godaddy/asherah/projects/1#card-24232177)

AEL-775

Core interfaces/types:

- MetastorePersistence (interface)
- RdbmsMetastorePersistenceImpl (replace "Rdbms" with whatever the golang sql package/api is, e.g. Jdbc for Java and Ado for C#... also not sure if Impl suffix is convention also used in go)
- MemoryPersistenceImpl (not sure if Impl suffix is convention also used in go)
- DynamoDbMetastorePersistenceImpl (not sure if Impl suffix is convention also used in go) – can probably defer for now
- Need to decide if we'll support load/store model to determine if we'll need (likely defer):
  - Persistence (interface)
  - AdhocPersistence
  - MemoryPersistenceImpl

**Comment by jpaskhay** [comment]
This was an experiment of trying to consolidate our internal tickets into this public repo. Closing this out as it's been handled internally, and the resulting work will be in our move of the Go codebase here.
