### ISSUE TITLE
Package: Crypto

### ISSUE THREAD

**Issue by sushantmimani** [godaddy/asherah#87]
Core interfaces/types (regardless of decision):

-  CryptoPolicy (interface)
- BasicExpiringCryptoPolicy
- can probably skip NeverExpiringCryptoPolicy?
- EnvelopeEncryptResult
- crypto related (should discuss level of abstraction currently in place):
  - MVP approach:
    - aes256gcm implementation and include whatever go package/api is being used as part of name somehow (e.g. BouncyCastle, Go if part of core lang, etc.)
  - Full abstraction approach (may not be possible in go):
    - AeadCrypto
    - AeadEnvelopeCrypto
    - (go package/api being used as subpackage here)
      - <GoPackageName>AeadCrypto
      - <GoPackageName>Aes256GcmCrypto

**Comment by jpaskhay** [comment]
This was an experiment of trying to consolidate our internal tickets into this public repo. Closing this out as it's been handled internally, and the resulting work will be in our move of the Go codebase here.
