### ISSUE TITLE
Package: Keys

### ISSUE THREAD

**Issue by sushantmimani** [godaddy/asherah#88]
Parent: [[GoLang] AE: Package Layout and Initial Refactor (first pass)](https://github.com/godaddy/asherah/projects/1#card-24232177)

AEL-778

Core interfaces/types:

- CryptoKey (interface)
- SecureCryptoKeyMap
- SecretCryptoKey
- SharedCryptoKey

**Comment by jpaskhay** [comment]
This was an experiment of trying to consolidate our internal tickets into this public repo. Closing this out as it's been handled internally, and the resulting work will be in our move of the Go codebase here.
