### ISSUE TITLE
Package: Utils

### ISSUE THREAD

**Issue by sushantmimani** [godaddy/asherah#89]
Parent: [[GoLang] AE: Package Layout and Initial Refactor (first pass)](https://github.com/godaddy/asherah/projects/1#card-24232177)

AEL-779

This is a bucket for any misc reusable functions, utils, etc. such as:

- JSON related helpers
- Metrics related
- anything else that manifested itself in Go

**Comment by jpaskhay** [comment]
This was an experiment of trying to consolidate our internal tickets into this public repo. Closing this out as it's been handled internally, and the resulting work will be in our move of the Go codebase here.
